wercker.yml

- The `file` command doesn't exist in the google/golang box, which
causes a bug when running github-upload-asset

Adding an explicit content type to the github asset uploader

---

git/git.go
git/git_test.go
launch.go
launch_test.go

- Adds a helper function that will return the url in https format.
- Adds functions to set the git user name and email
- Addresses #24

Use https as default url for git clone operation

---

data/screwdriver.yaml
executor/executor.go
launch.go
launch_test.go
screwdriver/screwdriver.go

This PR ties the api function `PipelineDefFromYaml` defined in #30 to the launch function
Adds an executor library that simply returns nil and should be called with the job to be executed

Incorporate api /validator call

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Please pay special attention when reviewing to try to catch any possible exit that would not correctly set the build status
- The command should exit 0 no matter what, to simplify job execution in
Kubernetes
- Build failures should give good log messages and set the status to
FAILED
- Unexpected errors that are not non-zero exit codes should result in
making the build failed
- A panic anywhere in the codebase should attempt to mark the build
failed, write a stack trace, and exit(0)

All code paths should now lead to marking the build success/failure

---

git/git_test.go
launch_test.go
wercker.yml

Apparently go 1.7 gets mad if you fail a test after the test is
complete. This means that our sloppy use of global function overrides
caught up with us.

Fixing the tests to work with go 1.7

---

git/git.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

- All HTTP calls will attempt to retry upon receiving 5XXs
- Default retry attempt is currently set to 5
- Exponential back off for up to ~1 minute (2s, 4s, 8s, 16s, 32s)
- Also refactors Screwdriver tests into tables
- Change const values into camelCase

Add retry wrapper for http calls

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

Rather than changing the directory in launch, we do so in executor.Run by passing in the path to the function.

Change dir of each command, Merge environment variables instead of overrwite

---

screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

- This was causing retries to contain an empty payload

Copying the payload to a string for POST retry

---

executor/executor_test.go
launch_test.go
screwdriver/emitter.go
screwdriver/emitter_test.go

- Previously reads were happening in a buffer, which could lead to
partial lines instead of waiting for newline
- Now we are using a Pipe to allow us to pull in STDOUT/STDERR from the command subprocesses.
This has the effect of creating a blocking pipe all the way through to the unix socket that we are 
writing to. We may need to buffer things in the future if we start to hit delays writing to the
logger service over the unix socket

Fixed a bug with partial line reads in the emitter

---

wercker.yml

We need this because the repo isn't reused between build and deploy

Bumping the tag in the deploy step

---

launch.go
launch_test.go

- This fixes go projects
- It's also an unnecessary bit of text in a workspace name
- New checkout: /sd/workspace/src/github.com/screwdriver-cd/launcher

Removing the .git portion of ScmURL

---

launch.go
screwdriver/emitter.go
screwdriver/emitter_test.go

This will allow us to emit information about the Screwdriver workspace
setup, and have it be associated with the sd-setup test

Associating emitter data with sd-setup by default

---

launch.go
launch_test.go

- If the container has an environment like this:
FOO="bar=baz"
we now set the correct value
- Added a test for environment generation

Improved environment population

---

screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

- Added a client timeout of 10 seconds
- Retries now happen for things like eof and timeout that have no http
response code
- Cleaned up some confusing log statements

Improving http retries

---

launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

- Change `parseScmUrl()` to `parseScmUri()`
- Now the method takes in `scmUri`, `scmRepo.name`  and `scmRepo.branch`

Update parseScmUrl() to take in scmUri and scmRepo

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

- Setting build environment variables can be done inside `createEnvironment` since it just reads from `build`. 
- Remove some unused code left from the previous refactoring

Refactor build environment creation

---

Dockerfile

Prevent overriding volumes in legacy containers.

[major] fix: change volume for launcher

---

data/emitter
launch.go
screwdriver/emitter.go
screwdriver/emitter_test.go

In the API we're naming all setup steps with `sd-setup-`
PRs needed:
- https://github.com/screwdriver-cd/build-bookend/pull/4
- https://github.com/screwdriver-cd/models/pull/143

feat: Switching to new naming convention `sd-setup-*` for startup commands [minor]

---

executor/executor.go
executor/executor_test.go
launch.go

Writing each command in the YAML to a temporary file in launcher. Instead of running the commands from YAML, source the temporary file to run the command.
Related to: screwdriver-cd/screwdriver#393

Launcher passes env variables between steps

---

launch.go
launch_test.go

In addition to the various Screwdriver-related environment variables, this PR aims to expose the Pipeline ID in an environment variable as well.

feat: expose pipeline id in build as environment variable

---

Dockerfile

/opt/sd is currently owned by root and when we try to write to it as any
other user (for example, to create the emitter directory), we run into
permission denied errors. We want Screwdriver to be able to be run as a
non-root user, so we need to give all users permissions to this
directory.

Give all users RW permission to /opt/sd

---

launch.go
launch_test.go

Adding the Build ID to the default environment that is exported from launcher. This is needed to be able to upload artifacts to the right Build directory (by ID) in S3.

fix: Add SD_BUILD_ID to default environment

---

Dockerfile
executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

To use meta-cli, `meta` of previous build is load from API and stored to temporary file before a build starting.
Also current `meta` is added to API payload with `UpdateBuildStatus`.
Related: https://github.com/screwdriver-cd/screwdriver/issues/293

feat: using meta-cli in launcher

---

executor/executor.go

Currently, if there is no newline in the output of `sourcing a step file`, the output will not be logged.
Because the output will be printed in the same line with  `guid  exitCode` which is filtered out of the log intentionally.
https://github.com/screwdriver-cd/launcher/blob/master/executor/executor.go#L47
Related to discussion in the end of the issue: https://github.com/screwdriver-cd/screwdriver/issues/293
Previously:
Now:

fix: force a newline after sourcing step file

---

launch.go
launch_test.go
screwdriver/screwdriver.go

`Build.Meta` is string and it caused JSON parse error when fetch previous Meta.
This PR provides:
- The type of `Build.Meta` to map[string]interface{} from string.
- Update tests for above fix.
Related: 
- https://github.com/screwdriver-cd/screwdriver/issues/293
- https://github.com/screwdriver-cd/screwdriver/pull/494

fix(293): type of previous meta to map[string]interface{}

---

launch.go
launch_test.go

This PR created symlink of `meta` to /usr/bin.
`meta` is executable in build (not only `/opt/sd/meta`).
I also tried to add `/opt/sd/` to PATH via `exec.Command("export", "PATH=$PATH:/opt/sd")`, but couldn't. So I used symlink.
<br>
This PR also fixed `TestFetchParentBuildMeta` condition of success.
Related: https://github.com/screwdriver-cd/screwdriver/issues/293

fix(293): add symlink of meta to /usr/bin

---

.gitignore
executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

This environment variable (`SD_API_URL`) will be read when publishing or validating a template in https://github.com/screwdriver-cd/template-main/pull/2

fix(470): Add API URL environment variable

---

Dockerfile

To use habitat in shared-step, this PR installs habitat in launcher. In addition, it installs sd-step go binary to wrap `hab` commands.
Detail is screwdriver-cd/screwdriver#300 .
This PR will be merged after https://github.com/screwdriver-cd/sd-step is built and released.

feat(300): install hab and sd-step in launcher

---

executor/executor.go
launch.go
launch_test.go

Add `/opt/sd` to PATH instead of creating symlink.
Because creating symlink requires root but it is not always the case.
Tested locally and works fine:

fix: add /opt/sd to PATH instead of creating symlink

---

executor/executor.go
executor/executor_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Have the executor run always run steps that have the `alwaysRun` flag set as `true`.
Pull requests to define the `alwaysRun` flag in steps (all should be merged together): 
https://github.com/screwdriver-cd/models/pull/155
https://github.com/screwdriver-cd/build-bookend/pull/8
https://github.com/screwdriver-cd/config-parser/pull/34
Related: https://github.com/screwdriver-cd/screwdriver/issues/473

feat(473): Always run steps with the alwaysRun flag true

---

.gitignore
.goreleaser.yml
Dockerfile
screwdriver.yaml

We'd like to build iOS apps in MacOS VMs.
Build and release for 64-bit macos. This PR uses goreleaser, see https://github.com/screwdriver-cd/log-service/pull/12 .
Please merge this PR after https://github.com/screwdriver-cd/log-service/pull/12, https://github.com/screwdriver-cd/meta-cli/pull/8, https://github.com/screwdriver-cd/sd-step/pull/4, otherwise the docker build fails.
Use jenkins executor for macos node : https://github.com/screwdriver-cd/executor-j5s/pull/12

feat: Build darwin/amd64 binary

---

executor/executor.go
executor/executor_test.go

Fixed the problem of reading long-lines.
See [this](https://golang.org/pkg/bufio/#Scanner) for more info:  
> Programs that need more control over error handling or large tokens, 
> or must run sequential scans on a reader, should use bufio.Reader 
> instead.
I pulled the helper function from: https://stackoverflow.com/a/12206365

	fix(#525): Move from bufio.Scanner to bufio.Reader

---

screwdriver.yaml

pin golang version to 1.8.3 for now as a temp fix so that we can roll out stjohn's change.
Related to https://github.com/screwdriver-cd/screwdriver/issues/729

fix: pin golang version to 1.8.3

---

launch.go

fix: expose build url as env

---

executor/executor.go
screwdriver/emitter.go

We have switched to `bufio.Reader` in the `executor.go` already.
But the log emitter inside launcher is still using `bufio.Scanner`. And there is no err handling for 
`fmt.Fprintln(w, t)` which is writing the log line to emitter. So now no err will be caught and the build will get stuck because emitter crashes.
Build image locally and tested it out, it works fine with long line now.
Related to https://github.com/screwdriver-cd/screwdriver/issues/525

fix: switch from bufio.Scanner to bufio.Reader for emitter

---

screwdriver.yaml

Using the git-tag script from `toolbox` repo to pull in the new git fingerprint. The toolbox repo has the new fingerprint and this will allow us to stop pinning to a specific golang version.
https://github.com/screwdriver-cd/screwdriver/issues/729

fix: Use toolbox repo for git scripts

---

launch.go
launch_test.go

Now, `PR-1:main` is allowed as job name in job model.
However, when job name is `PR-1:main`, SD_PULL_REQUEST is empty because prNumber's regexp doesn't match `PR-1:main`.
Fix prNumber's regexp

fix: can get prNumber even if job name is PR-1:main

---

Dockerfile

We've been getting `address not found` errors intermittently when trying to contact ha.pool.sks-keyservers.net during Docker image publish. Adding more key servers in hopes that our image versions can get published successfully on Docker..

fix: Add more key servers to Dockerfile

---

launch.go
launch_test.go
screwdriver/emitter.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Make extra API calls to check if the triggering build and the current build belong to the same pipeline. If they belong to the same pipeline, then we store `metadata` into the same `meta.json`. 
If the belong to different pipelines (meaning this is an external trigger), we store `metadata` into the triggering job `sd@123:component.json`
More implementation details here: https://github.com/screwdriver-cd/screwdriver/issues/771

feat: write external triggered metadata to a separate file

---

executor/executor.go

If previous user steps failed, we don't need to exit the shell.

fix: exit shell only if previous user steps succeed

---

executor/executor.go
executor/executor_test.go

Do not update step status for step not run.
if you have steps like this:
```
steps:
- print: echo $SD_PULL_REQUEST
- exit: exit 1
- echo: echo hello
- test: echo world
```
We shouldn't update step status for `echo` and `test`
Related to https://github.com/screwdriver-cd/screwdriver/issues/473

fix(133): do not update step status for step not run

---

launch.go
launch_test.go

Launcher set store url to job environment.
When we use sd-cmd, it will communicate with Store APIs. But now sd-cmd can not get Store url from job environment. Thus I make it possible to set store api in job environment by launcher.
Allow to add new argument of `store-uri` and set Store url in job environment by using the argument. 
The value of key is `SD_STORE_URL`.
[command document](https://github.com/screwdriver-cd/screwdriver/blob/master/design/commands.md)
[sd-cmd PR](https://github.com/screwdriver-cd/sd-cmd/pull/4)

feat: set store url to env

---

launch.go
launch_test.go

Revert this change to see where launcher breaks. 
https://github.com/screwdriver-cd/launcher/pull/137

fix: revert #137

---

Dockerfile

Currently, builds cannot run because it cannot download launcher's binary. So inside the build, `launch` is empty. 
for beta pods: `-rwxr-xr-x 1 root root       0 Jan  5 19:16 launch`
for prod pods: `-rwxr-xr-x 1 root root 5760224 Dec 12 01:18 launch`
Somehow this name got changed, probably by the `go-releaser`

fix: launcher release name got changed

---

README.md
_config.yml
executor/executor.go
executor/executor_test.go
launch.go
screwdriver.yaml

Our launcher is not getting shipped with the version number anymore due to the variable naming.  We also have the wrong date in the copyright.
Additionally, I changed the launcher to allow us to pass an alternative shell path and switching to `gopkg.in` for semver dependencies.

fix: GoReleaser bug and Alternative Shell

---

.gitignore
README.md
habitat/plan.sh

Right now our launcher depends on `/bin/sh` to be available in the container.  This will allow users to use `/bin/bash` as it can be bundled with the launcher via Habitat.
So this is accomplished by adding a wrapper script (`launcher`) that calls the real launcher (`launcher.real`) and passes the full path to the `/bin/bash` dependency.  It's based on how Habitat does [`bundler`](https://bldr.habitat.sh/#/pkgs/core/bundler/1.16.0/20171129183702).
More information about the GoScaffolding can be found [here](https://github.com/habitat-sh/core-plans/tree/master/scaffolding-go).

feat: Adding Habitat package

---

.goreleaser.yml
Dockerfile
habitat/plan.sh
screwdriver.yaml

This is to enable the Launcher container to now have a copy of Habitat-packaged Bash.  It doesn't change anything for the builds yet, but gives us the option of using it.
You could now use it by setting the following environment variable:
```bash 
$ SD_SHELL_BIN=`/opt/sd/bin/hab pkg path core/bash`/bin/bash
```
Also fixed it so that the Launcher is statically compiled and doesn't depend on the hack here: https://github.com/screwdriver-cd/launcher/blob/b8ff0ec9428c099c78dcb2710db17c8b1e109b3f/Dockerfile#L8-L9
We can remove that after all the other binaries are updated to be statically compiled.

feat(habitat): Pull in Bash Habitat.sh package

---

executor/executor.go
executor/executor_test.go
habitat/plan.sh
launch.go
launch_test.go
screwdriver.yaml
screwdriver/screwdriver_test.go

I moved `SD_SHELL_BIN` from a hidden environment variable to an argument that can be passed on the command line.
Also fixed startup and teardown to use the shell that was specified.
Finally, added some extra output to the start of the build to know more about the running job.

fix: Moving SD_SHELL_BIN to args and adding debug info to start

---

Dockerfile

To use sd-cmd in build, we have to install sd-cmd go binary in launcher as sd-step is installed.
Install sd-cmd go binary in launcher.

feat(677): Install sd-cmd in launcher

---

Dockerfile

This will allow the docker-executor to automatically mount this volume.
Related issue: https://github.com/screwdriver-cd/screwdriver/issues/877

feat(habitat): Expose Habitat as volume

---

.gitignore

Completely ignore the `glide.lock` file, since we don't leverage it in our build pipeline

chore: ignore glide.lock file

---

executor/executor_test.go
glide.yaml
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

When a user starts a detached job, it would be useful if they can use the meta from the entire parent event, rather than the parent build, since a detached job will not have a parent build ID.
This PR uses meta from the parent event when no parent build ID exists.
*There will be more work in the future for builds with multiple parent build IDs to use the aggregate meta from their parent build IDs to rerun.*
Related to https://github.com/screwdriver-cd/screwdriver/issues/904
Blocked by https://github.com/screwdriver-cd/data-schema/pull/209

fix: Get meta from parent event when no parent build ID

---

launch.go
launch_test.go

Skip fetching if no parent build, and not a restart
Fixing a bug from here: https://github.com/screwdriver-cd/launcher/pull/154
Related: https://github.com/screwdriver-cd/screwdriver/issues/904

fix: do not fetch event meta if not a restart

---

.goreleaser.yml

This removes the dependency on local libraries.  Basically making it work in an alpine container.
```
-d	disable dynamic executable
-s	disable symbol table
-w	disable DWARF generation
```
Also disable C linking: https://golang.org/cmd/cgo/

fix: Make the binary static

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

This is an initial proposal for killing a build after a period of time so they're not eating up system resources.
Further revisions will include:
* The ability to change the timeout limit
* Enforce a range of 15 minutes - 10 hours
Use a non-modifiable build timeout for killing builds that take longer than 90 minutes.
* [Build Timeout issue](screwdriver-cd/screwdriver#545)

feat: unmodifiable timeout

---

launch.go
launch_test.go

This extends the initial proposal for killing a build after a period of time so they're not eating up system resources.
Further revisions will include:
* Enforce a range of 15 minutes - 10 hours
Allow the build timeout for killing builds to be configurable. When not given an explicit value (whether through CLI flag or environment variable), use the default 90 minutes.
* [Build Timeout issue](https://github.com/screwdriver-cd/screwdriver#545)

feat: allow build timeout to be configured

---

launch.go
launch_test.go
screwdriver/screwdriver.go

When a join occurs, we're currently just using the meta from the last build that triggered the join job to start. For example, if C requires A and B, if A finishes running first, B will trigger C to start after it is done. C would then be run with whatever metadata B had.
```
A 
-->  C
B
```
We would like to merge all the metadata from all parent builds so that C can run using metadata from both A and B.
This PR checks for multiple parent build IDs and merges the metadata for all of them.
Related to https://github.com/screwdriver-cd/screwdriver/issues/904
Blocked by https://github.com/screwdriver-cd/data-schema/pull/210

feat: Merge parentBuildId metas

---

executor/executor.go
executor/executor_test.go

The blocking operation was masked by the `MockEmitter` stub. By forcing it to block the current process with a `time.Sleep`, we were able to replicate how the timeout wasn't being executed.
Execute the `doRunCommand` in a separate go routine.

fix: defer command execution to subprocess

---

launch.go

The parameter for `build-timeout` is currently seconds. We want to limit the level of granularity from seconds to minutes.
Change the Launcher interface from seconds to minutes.

feat: build timeout argument as minutes instead of seconds

---

screwdriver.yaml

Pull in new sd-cmd to use habitat format sd-cmd.
Related: https://github.com/screwdriver-cd/sd-cmd/pull/18

fix: pull in new sd-cmd

---

launch.go
launch_test.go

Currently only the first layer of JSON is merged when parallel jobs are joined together. Deeper layers replace each other. 
This PR uses a deep merge so that all parts of the metadata are preserved.
_Note: One caveat is that the second job will not overwrite the first's metadata if they have the same key. I think it's okay to have this behavior, since users cannot reasonably expect a certain result if they override the same meta key._
- Resolves https://github.com/screwdriver-cd/screwdriver/issues/1015
- Golang package: https://godoc.org/github.com/peterbourgon/mergemap

fix(1015): Deep merge metadata for join jobs

---

launch.go
launch_test.go

Some users would like to know what's in their metadata at the end of each build.
This PR exposes a path to the metadata file so users can cat it out or save it to artifacts if they choose.
Notes: Not sure what's a better name for it since there's already SD_ARTIFACTS_DIR, SD_SOURCE_DIR, SD_SOURCE_PATHS. Some ideas:
- SD_META
- SD_META_DIR
- SD_META_PATH
- SD_META_FILE
???
- Related to https://github.com/screwdriver-cd/launcher/pull/174
- Current environment variables: https://docs.screwdriver.cd/user-guide/environment-variables

fix: Add SD_META env variable

---

Docker/launcher_entrypoint.sh
Dockerfile

Docker 1.18 is unsupported due to a dependency's-dependency update in `containerd/continuity` where it fails to handle fifos files (which the `emitter` is).
Create the FIFO emitter at container start-up instead of creating it during the Docker image compilation. This should address issues with Docker 1.18 being unable to handle fifos files
Fixes screwdriver-cd/screwdriver#979
* screwdriver-cd/screwdriver#979

fix: defer emitter creation to container start-up

---

executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Calling Screwdriver API to get env vars from coverage plugins
Blocked by https://github.com/screwdriver-cd/coverage-sonar/pull/7
Related to https://github.com/screwdriver-cd/screwdriver/issues/1084

feat(1084): Add Sonar coverage env vars [2]

---

Docker/launcher_entrypoint.sh
Dockerfile

I'd like to fix the launcher so I can test out my change (https://github.com/screwdriver-cd/launcher/pull/180) but the launcher is broken from Darren's change, screwdriver-cd/launcher#177 (> v4.0.103).
See Darren's comment https://github.com/screwdriver-cd/screwdriver/issues/979#issuecomment-394546810
Reverts screwdriver-cd/launcher#177

Revert "fix: defer emitter creation to container start-up"

---

screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Remove extra slash in coverage/info endpoint
Related to https://github.com/screwdriver-cd/screwdriver/issues/1084

fix(1084): Remove extra slash

---

launch.go
launch_test.go

Launcher failed to launch a build by getting coverage info failure with API which doesn't have coverage plugin.  
This PR allows to use API without coverage plugin.

fix: allow to use API without coverage plugin

---

Docker/launcher_entrypoint.sh

We want the Docker entrypoint script to be what the executor's entrypoint is hardcode at (e.g., https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.tim#L21). This way, we can incorporate some pre-launch steps before starting the `launcher` and `logservice` processes. 
This needs either a *major* or a *minor* version bump
Update the command to perform the exact same command that all (as of today) executor libraries use to initiate the build.
* screwdriver-cd/screwdriver#979
* Executor entrypoints
* `executor-k8s` - https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.tim#L21
* `hyperctl-image` - https://github.com/screwdriver-cd/hyperctl-image/blob/master/scripts/hyper-pod-template.json#L12

refactor docker entrypoint command

---

launch.go
launch_test.go

Since we are supporting `meta` as a payload attribute for POST `v4/events`, we need to write that value  into `metaFile` as part of the launch process
If the event contains `meta` it should be written into `/sd/meta/meta.json`. 
If for some reason the event contains `meta` AND it has a `parentEventId` OR `parentBuildId`. The `meta` of the parents should take precedence.
Additionally cleaning up a few other tests.
https://github.com/screwdriver-cd/screwdriver/issues/1113

[3] feat(1113): Write event meta if it exists

---

executor/executor.go
executor/executor_test.go

Allow user-defined teardown steps. They will be run in separate shells, just like the screwdriver teardown steps. 
_**Will look into passing environment variables in a second pass.**_ 
Related: https://github.com/screwdriver-cd/screwdriver/issues/1126

feat: support user-teardown

---

Dockerfile

Otherwise it won't work here: https://github.com/screwdriver-cd/executor-k8s/blob/master/config/pod.yaml.tim#L22

fix: copy optional entrypoint script to launcher image

---

executor/.#executor.go
executor/executor.go

Just `teardown` step should not be added to user defined teardown. It may work unintentionally if users already use `teardown` step name.
This PR fixes regexp not to include just `teardown` step.
It also does some refactor.

fix: [small] fix teardown regexp

---

Dockerfile

https://github.com/screwdriver-cd/artifact-bookend/pull/23
To be able to zip artifact files before uploading to store, we need `zip` in all the images
PR to zip artifacts before uploading - https://github.com/screwdriver-cd/artifact-bookend/pull/23

Add core/zip from habitat

---

executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

For issue https://github.com/screwdriver-cd/screwdriver/issues/1167 , we should exchange temporary JWT token in launcher.
I added GetBuildToken func to screwdriver API interface, and execute it before launchAction.
After get build token, create API using that token.
issue: https://github.com/screwdriver-cd/screwdriver/issues/1167
related PR:
executor-k8s: https://github.com/screwdriver-cd/executor-k8s/pull/88
executor-k8s-vm: https://github.com/screwdriver-cd/executor-k8s-vm/pull/35
executor-docker: https://github.com/screwdriver-cd/executor-docker/pull/27
executor-jenkins: https://github.com/screwdriver-cd/executor-jenkins/pull/23
executor-base:

feat(1167): [1][medium]get build token before launchAction

---

Docker/run.sh
Dockerfile
launch.go

To fetch build token in actual build execution, we fixed to exchange temporal token to build token in launcher process. 
However, also log-service uses token which is passed by `executor-*`.
To pass fetched build token to log-service and launcher, add the flag to launcher which only fetch token in launcher process, and use this flag to set fetched token before launcher and log-service processes start.
Detail: https://github.com/screwdriver-cd/screwdriver/issues/1167#issuecomment-409441739
Add flag to only fetch build token in launcher process.
Add wrapper script to run build in multiple executors.
issue: https://github.com/screwdriver-cd/screwdriver/issues/1167
issue comment: https://github.com/screwdriver-cd/screwdriver/issues/1167#issuecomment-409441739
PR:
executor-k8s: …

feat(1167): [4][small] Add fetch flag

---

executor/executor.go
executor/executor_test.go
executor/script.sh
launch.go
launch_test.go
screwdriver.yaml

Passing environment variables to teardown steps
In `trap`, we do `env` to a file and do proper parsing:
- escape double quote
- add double quotes around the value
In beginning of each teardown, we source the file
Related: https://github.com/screwdriver-cd/screwdriver/issues/1192

fix: Pass env to teardown

---

Docker/run.sh

In the run.sh, `SD_TOKEN` is temporally defined, therefore it cannot be used from environment variables in the process. 
```
mkfifo: cannot create fifo '/opt/sd/emitter': File exists
[WARN  tini (8)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
2018/08/06 22:07:43 Launcher process only fetch token.
2018/08/06 22:07:43 No JWT specified. Cannot upload.
Usage of /opt/sd/logservice:
-api-uri string
Base URI for the Screwdriver API ($SD_API_URL)
-build string
ID of the build that is emitting logs ($SD_BUILDID)
-emitter string
Path to the log …
```

fix(1167): fix run script

---

executor/executor.go
executor/executor_test.go
launch.go

It's possible that during this part, `$newfile` exists and the check for it in `doRunTeardown` passes and tries to source the env file. 
```
sed '/^PS1=.*/d' $file > $newfile &&
mv $newfile $file
```
This PR uses a different filename and make $newfile only available at the end

fix: write nops1 to a different file

---

executor/executor.go
executor/executor_test.go

Currently, if the `env_export` file is not available then it will wait forever. 
Adding this to timeout after 5 seconds.

fix: Add timeout for wait

---

Dockerfile
screwdriver.yaml

This may fix a bug of missing files with Docker 18.03.0-ce.
These executors were already updated.
- https://github.com/screwdriver-cd/executor-docker/blob/b511eedee2e01c22d7d401f186c00fbdae3aca15/index.js#L175
- https://github.com/screwdriver-cd/executor-k8s/blob/91bcd9999b0693327dda03a652677d48665e82c7/config/pod.yaml.tim#L22
blocked by: https://github.com/screwdriver-cd/hyperctl-image/pull/25 -> merged
Related issue: https://github.com/screwdriver-cd/screwdriver/issues/979

feat(979): [small] update docker entry point and remove mkfifo from Dockerfile

---

Docker/launcher_entrypoint.sh

if the user of the image is not root, we need to do `sudo mkfifo -m 666 /opt/sd/emitter` to create it

fix(979): fix entrypoint mkfifo cmd with proper user

---

Docker/launcher_entrypoint.sh
Docker/run.sh

cannot mkfifo `/opt/sd/emitter` for k8s-vm since the share mount /opt/sd is `read-only`
https://git.ouroath.com/cocktails-screwdriver/hyperctl-docker/blob/master/scripts/hyper-pod-template.json#L23

fix(979): change the emitter path

---

Dockerfile

cache hab docker pkg and dependencies so that inside the build we don't rely on habitat to fetch pkgs

fix: cache hab docker pkg

---

executor/executor.go

Don't fail if it cannot export the env file during teardown
Cannot change `set -e` because we still want to exit & trap if the build command fails.

fix: do not fail if cannot export ENV

---

Dockerfile

Install store-cli in launcher
~~Waiting for store-cli to go out first.~~
related: 
https://github.com/screwdriver-cd/screwdriver/issues/1282
https://github.com/screwdriver-cd/screwdriver/issues/1257

fix(1257): install store-cli

---

launch.go
launch_test.go

Some build pods is running forever although it's build token is invalid and builds is not executed.
```
$ kubectl get pod 
NAME                                READY     STATUS    RESTARTS   AGE
36934-7prwc                         1/1       Running   0          1d
```
The build pod's log is below.
```
[WARN  tini (10)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
2018/11/13 11:01:23 Error getting Build Token 36934: Posting to Build Token: 404 Not Found: Build does not exist
2018/11/13 11:01:23 Starting Build 36934
2018/11/13 11:01:23 No JWT …
```

fix: validate token

---

Docker/launcher_entrypoint.sh
Docker/run.sh

I think an _exec_ for tini would be better here.  It used to be that tini was the entrypoint, and thus it was PID 1.  Now it is being run as a subshell from the new entrypoint launcher_entrypoint.sh.  This change causes tini to replace launcher_entrypoint as PID 1. I have tested in my environment and it seems to work properly.  This would only be an issue in long running docker jobs that have many steps, eventually you might run out of file descriptors or something.

exec tini instead of subshell tini

---

Dockerfile

cache wget in launcher since the REPO feature will need that.

fix: cache wget in launcher

---

Dockerfile

add sed to launcher cache to resolve the warning from new hab git cmd

fix: add sed to launcher cache

---

screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

- init step has no actual cmd to be executed, it's just a placeholder for build stats.
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1270

fix: skip init step [1]

---

screwdriver/screwdriver.go

we're seeing some network delay and cause some timeout err,  increase http request timeout from 10s to 20s
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1443

fix: increase http request timeout

---

Dockerfile

- add hab unzip cache since we're using it in the coverage bookend

fix: add hab unzip cache

---

launch.go
launch_test.go

Previously, it will only create default meta for builds that have parentBuild, parentEvent, etc.

fix: create default meta for regular builds

---

launch.go
launch_test.go

namespace default meta under `build`
Related: https://github.com/screwdriver-cd/screwdriver/issues/1483

fix(1483): namespace build

---

launch.go
launch_test.go

Use `parentBuildID` instead of `build.ParentBuildID`, since that will through the [convertToArray logic](https://github.com/screwdriver-cd/launcher/blob/70fae824437541eee50167f96aa7ac804403fbe4/launch.go#L183-L188). This will solve the overflow problem. However, it will create a side effect that if single parent build ID, it'll still be an array (eg: `[1234]` instead of `1234`)
Related: https://github.com/screwdriver-cd/screwdriver/issues/1515

fix: SD_PARENT_BUILD_ID is overflow 

---

Dockerfile

Adding another key server based on another example found here: https://github.com/nodejs/docker-node/blob/9e126c900676db68a1bb8c993565d1459280bf23/11/alpine/Dockerfile#L33-L35
Related to https://github.com/screwdriver-cd/launcher/pull/128, https://cloud.docker.com/u/screwdrivercd/repository/registry-1.docker.io/screwdrivercd/launcher/timeline

fix: Add another key server

---

Docker/run.sh

The flag is not getting read when it is at the end of the command. Moving it to the middle.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1555

fix(1555): Switch order of run.sh flags

---

launch.go

`metaFile` is overwritten when there is an external triggered job.
`SD_META_PATH` should always point to the path of the current job meta, which is `{metaSpace}/meta.json`

fix: SD_META_PATH points to correct path

---

Dockerfile

our alpine version is a lot behind and using a pretty old version of busybox with limited cmds. Upgrade it to 3.8. Latest is on 3.9 and actively being worked on.

fix: update alpine version

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

Currently it's hanging at exporting `PS1`
This PR separates the OS env from the build env. For OS env, still use `append(osEnv, c.Env...)`. For build env, will write to a file and source inside the `sd-setup-launcher` step. 
Tested in beta

fix(1070): separate OS env

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

Doing expansion in `go` rather than doing it in the shell, since we get into different parsing issues. 
Thanks @jithin1987  for suggestions.

fix(1590): expandEnv

---

launch.go
launch_test.go

now we pre-populate some build meta about commit in the model, when we create the meta for a build, we should merge those.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1437

fix: merge build predefined meta

---

launch.go
launch_test.go

set SD_SOURCE_DIR properly when pipeline has rootDir
Related to: https://github.com/screwdriver-cd/screwdriver/issues/1455

fix(1455): set SD_SOURCE_DIR properly when pipeline has rootDir (2)

---

launch.go
launch_test.go

Will fix by passing the cluster env as API config, and inject into build.Environment

fix: Revert "fix: add default cluster env"

---

executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

We can merge this, but it needs to deploy at the same time as our API (https://github.com/screwdriver-cd/screwdriver/pull/1600)
Otherwise, it will break. 
- If API gets deployed first, API returns array but launcher expects object.
- If launcher gets deployed first, API still returns object and launcher expects an array. 
We might need some downtime to deploy this change. 

fix: accept env as array. BREAKING CHANGE: build environment is now an array

---

Dockerfile

pin hab version since the latest one requires us to accept a chef license. Our docker builds are failing becausue of this.
ref: https://forums.habitat.sh/t/habitat-0-81-0-released/1095

fix: pin hab version

---

launch.go
launch_test.go

Add an new env `SD_CHECKOUT_DIR`. Later on, inside the scm-github, we will checkout at this checkoutDir. If you don't have custom `rootDir`, this will be the same as the SD_SOURCE_DIR. Otherwise `SD_CHECKOUT_DIR` will still be the path to the repo root dir, but `SD_SOURCE_DIR` will be `SD_CHECKOUT_DIR/rootDir`.
We need to separate this out so that when we clone, it will always clone to the root. And then we can cd to the proper source dir.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1455

 fix(1455): add SD_CHECKOUT_DIR

---

launch.go
launch_test.go

SD Secrets are often used for passing some passwords like XaaS. 
Those passwords sometimes include `$` or any other expandable char.
This PR fixed not to expand Secrets.
Related Issues:
- https://github.com/screwdriver-cd/screwdriver/issues/1670
- https://github.com/screwdriver-cd/screwdriver/issues/1070

fix(1670): fix not to expand Secrets

---

launch.go

when using with subDir, the working directory should be `subDir`, not `w.Src`.
Related: https://github.com/screwdriver-cd/screwdriver/issues/1455

fix: cmdPath when running with sourceDir

---

executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

Currently, when users checkout at a subdirectory for example: `test` then 
during user command pwd = `/sd/workspace/src/github.com/d2lam/testSubDir/test`
during teardown pwd = `/sd/workspace/src/github.com/d2lam/testSubDir`
This is because in our setup, we `cd` into the subDir. Therefore, teardown steps need to change its directory path. 
Related: screwdriver-cd/screwdriver#1455

fix: set workDir for subDir

---

launch.go
screwdriver.yaml

Screwdriver build shell is interactive. Setting GIT_PAGER until https://github.com/screwdriver-cd/screwdriver/issues/1583#issuecomment-539677403 is resolved.
Set GIT_PAGER environment variable
1. https://git-scm.com/docs/git#Documentation/git.txt-codeGITPAGERcode
1. https://stackoverflow.com/a/2183920/256400

fix: set GIT_PAGER

---

launch.go
launch_test.go

Implementation of https://github.com/screwdriver-cd/screwdriver/issues/1866
One less thing to worry about when running jobs and expecting workspace containment

Support for SD_META_DIR environment variable

---

launch.go

event-cache-dir declared twice 
remove event-cache-dir redeclaration 
[1830]

fix(1830): fix redeclaration error for event-cache-dir

---

Dockerfile

Docker install command errors as docker-containerd, docker-containerd-ctr, docker-containerd-shim missing in habitat core/docker/19.03.3 version
Pin down habitat core/docker version to 18.03.0

fix(1830): docker folders missing in 19.03.3 version pin to 18.03.0

---

.goreleaser.yml

Not able to cherry-pick the folder or file in a directory and store or retrieve the cache.
Pull the latest store-cli package which has the fix for build-cache disk-based strategy to cherry-pick the folder or file.
https://github.com/screwdriver-cd/screwdriver/issues/1906

fix(1906): pull latest store cli

---

launch.go

If files to be cached are more than 15000, store-cli throws runtime error 10000-thread limit and the cache-max-size-mb argument to be read as a string instead of Int64 
This PR 1. gets the latest store-cli which has changes related to reduce md5check concurrency process limit to 3000 from 10000 and 2. update cache-max-size-mb argument to be read as a string instead of Int64 to handle docker error when sd is run locally.
[1928](https://github.com/screwdriver-cd/screwdriver/issues/1928)

fix(1928): store-cli - runtime error 10000 thread limit

---

screwdriver.yaml

Tests do not run recursively. It tests only `launch`. 
https://cd.screwdriver.cd/pipelines/21/builds/169248/steps/test
- Run test recursively.
- Refactor some steps.
https://github.com/screwdriver-cd/meta-cli/blob/master/screwdriver.yaml

fix: run test recursively and refactor steps

---

screwdriver/screwdriver.go

`handleResonse` is currently run outside of retry handler. But in `golang` Timeout in inclusive of time spent in parsing response body.
Bring `handleResponse` function under retry protection for timeout.
1. https://github.com/screwdriver-cd/launcher/blob/master/screwdriver/screwdriver.go#L223-L247
2 https://golang.org/pkg/net/http/#Client
```
The timeout includes connection time, any
// redirects, and reading the response body.
```

fix: bring handleResponse under retry purview

---

Dockerfile
launch.go
launch_test.go
screwdriver/screwdriver_local.go
screwdriver/screwdriver_local_test.go
screwdriver/screwdriver_test.go

`sd-local` mounts workspace from host filesystem, but launcher check it has already existed, and if so launcher throws error.
To avoid this, this PR makes launcher not to throw that error.
And, we forgot to copy `local_run.sh` to Docker Image.
And furthermore, we want to use `/sd/workspace/src/{dummyScmHost}/{dummyScmOrg}/{dummyScmRepo}` as source directory in local-mode
- make `createWorkspace` function not to throw error about `path already exists` in local-mode
- copy `local_run.sh` to Docker Image
- fix dummy `Pipeline` information
screwdriver-cd/screwdriver#1314
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright …

fix(1314): Fix about local-mode

---

Docker/run.sh

Top images to be cached in the node are not available as part of the node warm-up.
Send image metrics to Prometheus via pushgateway configuration. These metrics will be used to query top n images and cached in node as part of the node warm-up. Environment variables are passed from executor-k8s.
When Docker/run.sh is called via executor-k8s-vm, it will skip metrics push to Prometheus. It's already implemented via hyperctl-docker scripts.
[Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
[Executor-k8s PR-117](https://github.com/screwdriver-cd/executor-k8s/pull/117)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make …

feat(818): push image metrics to prometheus

---

Docker/run.sh

missing NODE_ID metrics and metrics not pushed due to invalid pushgateway url config
added NODE_ID to metrics and updated pushgateway url config
[Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)

feat(818): add nodename to metrics, upd pushgateway url

---

Docker/run.sh

cat <<EOF syntax doesn't send data when curl runs in the background; content-length is 0.
Simplify curl call, pass data to curl via echo.
[Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)

feat(818): simplify curl call

---

Docker/launcher_entrypoint.sh

Symlink hab cache, log pipe and launcher missing which is required for kata.
Symlink hab cache, log pipe and launcher configuration updated in the launcher. The Source of truth for this script is from hyper setup.sh.

feat(818): update hab, log pipe n launch setup

---

executor/executor.go

Currently, setup-launcher command logs are shown in following steps command when use sd-local.
```
sd-setup-launcher: Screwdriver Launcher information
sd-setup-launcher: Version:        v6.0.49
sd-setup-launcher: Pipeline:       #0
sd-setup-launcher: Job:            test
sd-setup-launcher: Build:          #0
sd-setup-launcher: Workspace Dir:  /sd/workspace
sd-setup-launcher: Checkout Dir:     /sd/workspace/src/screwdriver.cd/sd-local/local-build
sd-setup-launcher: Source Dir:     /sd/workspace/src/screwdriver.cd/sd-local/local-build
sd-setup-launcher: Artifacts Dir:  /sd/workspace/artifacts
init: $ echo 'Init step'
init: set -e && export PATH=$PATH:/opt/sd && finish() { EXITCODE=$?; tmpfile=/tmp/env_tmp; exportfile=/tmp/env_export; export -p | grep -vi "PS1=" > $tmpfile && mv $tmpfile …
```

fix(1314): export setup log before following steps are executed

---

Docker/run.sh
launch.go
launch_test.go

metrics missing in kata route
Add metrics sd_build_scheduled, sd_build_image_pull_duration_secs, sd_build_launcher_duration_secs

feat(818): add metrics

---

Docker/launcher_entrypoint.sh

sd-setup-launcher failed with error mkdir /sd/meta: permission denied
Add full permission to /sd directory

fix(818): add full permission to sd folder

---

Docker/run.sh
launch.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Simplify metrics API call and add two more metrics
This PR simplifies three different metrics API calls to single API call and add sd_build_time_secs and sd_build_queued_time_secs metrics.

fix(818): add more metrics

---

Docker/launcher_entrypoint.sh

Build starts and status changes to Running but crashes immediately for some containers.
Enable additional logging in launcher entry point to narrow down the root cause.

fix(818): enable logging launcher entrypoint

---

Docker/launcher_entrypoint.sh
Dockerfile

Error when running docker in kata containers for docker versions below 19.03.0.
Error: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"could not create session key: function not implemented\"": unknown 
Upgrade docker version to 19.03.8 and use hab pkg anonymous/docker published by @DekusDenial.

fix(818): docker in kata containers

---

Docker/launcher_entrypoint.sh

Symlink hab anonymous docker packages
[PR#347-docker in kata containers](https://github.com/screwdriver-cd/launcher/pull/347)

fix(818): create symlink for hab anonymous docker packages

---

Docker/launcher_entrypoint.sh
Dockerfile

Install docker from hab core/docker, revert changes related to [PR#347](https://github.com/screwdriver-cd/launcher/pull/347), [PR#348](https://github.com/screwdriver-cd/launcher/pull/348)
also added jq per @DekusDenial request

fix(818): install docker from hab core/docker

---

Docker/run.sh
launch.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

With the existing metrics, not able to plot a graph trend for builds running vs completed.
Include sd_build_status metrics, to show running vs completed (success, failure, aborted) trend

fix(818): upd to include sd_build_status metrics

---

launch.go

pushMetrics doesn't trigger randomly.
Moving pushMetrics function to the top of the exit function to narrow down the issue.

fix(818): randomness in pushmetrics

---

Docker/run.sh
launch.go

pipeline-id/job-id/build-id is available in both beta and prod environments, which results in incorrect metrics.
add sd environment to metrics data
[Executor PR-126](https://github.com/screwdriver-cd/executor-k8s/pull/126)

fix(818): add sd environment to sd metrics

---

Dockerfile

Pin docker version. Any upgrade to the docker version should be tested prior to pinning version.

fix(818): pin docker version

---

executor/executor.go
executor/executor_test.go

It will be useful for teardown steps to be aware of the build status thus far inferred from the exit codes from previously executed steps.
To include previous steps exit code as env var inside a teardown step
https://github.com/screwdriver-cd/screwdriver/issues/2103

fix: expose step exit code and pass to teardown

---

Docker/local_run.sh

Copy paste from https://github.com/screwdriver-cd/launcher/blob/master/Docker/launcher_entrypoint.sh#L17-L26
Attempt to make Docker available in local mode. 

fix: try mounting hab packages in local mode

---

screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

The environment variables for retry exist separately in launcher and log-service, so we unify them.
- rename `LAUNCHER_SDAPI_TIMEOUT_SEC` to `SDAPI_TIMEOUT_SECS`
- rename `LAUNCHER_SDAPI_MAXRETRIES` to `SDAPI_MAXRETRIES`
https://github.com/screwdriver-cd/launcher/pull/357#discussion_r444359365
https://github.com/screwdriver-cd/log-service/pull/35

fix: Unify environment variables for retry

---

.gitignore
Dockerfile

Upgrade sonar-scanner-CLI to the latest 4.4.0.2170 released June 23, 2020.
Upgrade alpine from 3.8 to 3.12 to fix unzip errors `lchmod (file attributes) error and unzip: compressed symlink is not supported` and download and unzip sonar-scanner-CLI 4.4.0.2170 (Linux and Mac).
[https://github.com/screwdriver-cd/coverage-sonar/pull/38](https://github.com/screwdriver-cd/coverage-sonar/pull/38)
[sonar-scanner-cli:4.4.0.2170](https://github.com/SonarSource/sonar-scanner-cli/releases/tag/4.4.0.2170)
[sonar-scanner-cli:3.3.0.1492...4.4.0.2170](https://github.com/SonarSource/sonar-scanner-cli/compare/3.3.0.1492...4.4.0.2170)
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to …

fix: upgrade sonar scanner cli

---

data/emitter
executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_local.go
screwdriver/screwdriver_local_test.go
screwdriver/screwdriver_test.go

It would be nice if users could see their project key and name as env vars in their builds.
This PR modifies the call to get coverageInfo so more environment variables can be passed back.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2152

fix(2152): Support more coverage env vars [4]

---

Dockerfile

Build with ci/dockercloud failed, and no new [launcher docker image](https://hub.docker.com/r/screwdrivercd/launcher/tags?page=1) has been created.
https://github.com/screwdriver-cd/launcher/commits/master
When I tried to do a docker build on my local machine, I got the following error.
```
/bin/sh: gpg: not found
```
In alpine 3.10 or later, the virtual parameter must be unique.
https://github.com/alpinelinux/apk-tools/commit/b45415b1096e76f40b32326d2798123f81fe5976

fix: Dockerfile for alpine:3.12

---

data/emitter
executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_local.go
screwdriver/screwdriver_local_test.go
screwdriver/screwdriver_test.go

Use coverage scope data present in Job endpoint for `/coverage/info` endpoint to re-use existing info 
https://github.com/screwdriver-cd/screwdriver/issues/2152

feat(2152): pass coverage scope to coverage info end point

---

data/emitter
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

```
2020/08/04 18:59:56 [DEBUG] GET https://api.screwdriver.cd/v4/coverage/info?jobId=7461&pipelineId=1077&jobName=main&pipelineName=jithine/sd-test&scope=&prNum=&prParentJobId=0
2020/08/04 18:59:56 Failed to get coverage info for build 432950 so skip it
```
https://play.golang.org/p/2lULPLFnhxS

fix:  support mixed data types for coverage info endpoint

---

data/emitter
launch.go
launch_test.go

UI and clients with build data need an easy way to query Sonar coverage data. For this caller needs access to Sonar Project Key without having to re-compute it again.
Add sonar project key into  metadata at `build.coverageKey`
https://github.com/screwdriver-cd/screwdriver/issues/2152

fix(2152): add coverageKey to build meta

---

Docker/launcher_entrypoint.sh

Launcher entry point is not exiting on error, leading to Kubernetes build pods stuck forever.
Exit launcher entry script on error

fix: exit launcher script on error

---

launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_local.go
screwdriver/screwdriver_local_test.go
screwdriver/screwdriver_test.go

Add `SD_SCHEDULING_BUILD` for periodic build.
If the build is triggered by scheduler, `SD_SCHEDULING_BUILD` is `true`.
Otherwise, `SD_SCHEDULING_BUILD` is `false`.
If there are any other appropriate environment name, I'll fix the environment name.
If an event is created by scheduler, event's creator username is `sd:scheduler`.
https://github.com/screwdriver-cd/queue-service/blob/415aa19006f30be7e69753c8736eb03bf3d9c1ea/plugins/queue/scheduler.js#L46-L54
In such case, set env `SD_SCHEDULING_BUILD` true.
https://github.com/screwdriver-cd/screwdriver/issues/2084

feat(2084): Add env for periodic build

---

Docker/launcher_entrypoint.sh
data/emitter
executor/executor_test.go
launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_local.go
screwdriver/screwdriver_local_test.go
screwdriver/screwdriver_test.go

Build hangs indefinitely in init step for any error in launcher_entrypoint.sh (e.g. default user root or sudo NOPASSWD not enabled in container). At cluster level, build terminates with error but error is not propagated back.
This PR will trap termination signals from launcher_entrypoint script and for any error it will update build with status `Failure` and message `Error: Build failed to start. Please check if your image is valid with curl, openssh installed and default user root or sudo NOPASSWD enabled`. Part of it for e.g. invalid container image is already handled in executor-k8s.
https://github.com/screwdriver-cd/executor-k8s/pull/138
https://github.com/screwdriver-cd/executor-k8s/pull/139
https://github.com/screwdriver-cd/executor-k8s/pull/140 …

fix: init container stuck/hang for errors

---

go.mod
go.sum

Missed to upgrade creack/pty in my previous PR, resulting in syntax error with creack/pty v7 - /opt/sd/launcher_entrypoint.sh: 5: /opt/sd/launcher_entrypoint.sh: Syntax error: "(" unexpected
Upgrade creack/pty v11
https://github.com/screwdriver-cd/launcher/pull/372

fix: creack/pty syntax error

---

Docker/launcher_entrypoint.sh

sd-local build fails with error "/opt/sd/launcher_entrypoint.sh: trap: line 5: /bin/echo set up bin: invalid signal specification". Suspecting becoz of EXIT signal. Removing EXIT signal from trap.
https://github.com/screwdriver-cd/launcher/pull/374

fix: sd-local build error

---

Docker/launcher_entrypoint.sh

sd-local build fails with error "/opt/sd/launcher_entrypoint.sh: trap: line 5: /bin/echo set up bin: invalid signal specification". 
Issue is due to passing argument $@ to trap cleanup function ("cleanUp $@"). This PR stores $@ into a variable in the start and then reads the variable inside cleanUp function.
https://github.com/screwdriver-cd/launcher/pull/375
https://github.com/screwdriver-cd/launcher/pull/374

fix: sd-local build throw syntax error

---

Docker/launcher_entrypoint.sh
Docker/run.sh
Dockerfile
executor/executor.go
executor/executor_test.go
launch.go
launch_test.go

Currently if a build is aborted the teardown steps don't run and hence generated artifacts are not available in this case.
This PR adds change to capture terminate signal and run the teardown step in the current build
https://github.com/screwdriver-cd/screwdriver/issues/1125

feat: Run teardown steps on abort build

---

Docker/local_run.sh

sd-local failed with an error 
```
mkfifo: cannot create fifo ‘/sd/emitter’: Permission denied
```
This happens if `/sd` already exists

fix: add smart_run

---

Docker/local_run.sh

Containers with non-root user is not working with `sd-local`

fix: handle non-root build containers

---

executor/executor.go
launch.go
launch_test.go

Currently if a build is aborted the custom user teardown steps don't run and hence additional processing on teardown is not configurable.
This PR adds change to run the users teardown steps along with the sd teaerdown in a build
https://github.com/screwdriver-cd/screwdriver/issues/2301

feat: add user teardown steps on abort

---

data/emitter
launch.go
launch_test.go

Users with external join jobs are finding that rerunning an old commit is pulling in stale external metadata.
This PR will check if parent build is from an external pipeline or not. If so, write meta to external file as well as merge meta to main build's meta. Also deletes stored local meta for external key.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2278

fix(2278): Update external files for join job meta

---

data/emitter
launch.go

We need to reset the local version of external meta so it can be fetched from the external file, since meta-cli will check local version first, then check external file: https://github.com/screwdriver-cd/meta-cli/blob/master/meta.go#L86
This PR checks if a local version of the desired external meta exists, then sets it to `null`. 
Related to https://github.com/screwdriver-cd/screwdriver/issues/2278

fix(2278): Reset local version of external meta

---

launch.go
launch_test.go

When using chain PR, the same PR comments are sent multiple times.
Reset summary to empty at the start of the build.
https://github.com/screwdriver-cd/screwdriver/issues/1858

fix(1858): Empty the summary in meta at the start of the build

---

launch.go
launch_test.go

I made a mistake in my previous PR https://github.com/screwdriver-cd/launcher/pull/384. The correct one is `meta.summary`.
https://github.com/screwdriver-cd/screwdriver/issues/1858

fix(1858): the path of meta.summary is wrong

---

Dockerfile

Tini init file got removed as part of this PR# https://github.com/screwdriver-cd/launcher/pull/369/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L42. Builds scheduled to run via executor-k8s-vm hyper route fails due to missing tini.
Add tini.
https://github.com/screwdriver-cd/screwdriver/issues/1125
https://github.com/screwdriver-cd/launcher/pull/369

fix: add tini to Dockerfile

---

Dockerfile

Display the docker image sha in the init or compatibility bookend to examine it for diffs or backtrack purpose.
Add Skopeo, Skopeo is a command-line utility that performs various operations on container images and image repositories.
Comparing image digests docker n skopeo
`docker images --digests`
| Image | sha256 |
| :--- | :--- |
|alpine:latest|sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378   
|ruby:2.5.5|sha256:219b0f233f8214793ccc8cdc787224dc6cfb728e98af9ea2c991f23bf1aee1ab   
`./skopeo inspect docker://docker.io/alpine:latest
./skopeo inspect docker://docker.io/ruby:2.5.5`
| Image | Digest |
| :--- | :--- |
|alpine:latest|sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378   
|ruby:2.5.5|sha256:219b0f233f8214793ccc8cdc787224dc6cfb728e98af9 …

fix: add skopeo binary

---

Docker/launcher_entrypoint.sh

jq: command not found in sd setup steps since jq is not binlink'd.
binlink hab jq
https://github.com/screwdriver-cd/launcher/pull/390

fix: binlink hab jq

---

executor/executor.go

when vespaengine/vespa-build-centos7 image is used; the export command is not overwriting and waiting for input.
Force overwrite environment commands file

fix: force env file overwrite

---

Dockerfile.local
executor/executor.go
executor/executor_test.go

Env variables not available in teardown steps
Capturing Interrupt and Term signal works differently for different shells. Update trap to handle ABRT signal to capture signal as expected.
https://github.com/screwdriver-cd/launcher/pull/401
https://github.com/screwdriver-cd/launcher/pull/396
https://github.com/screwdriver-cd/launcher/pull/394
https://github.com/screwdriver-cd/launcher/pull/388
Related to https://github.com/screwdriver-cd/screwdriver/issues/2361

fix: Env variables not available in teardown steps

---

launch.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

`json.Unmarshal` does not support nested key in struct tag. This PR makes `Build` struct possible to have `QueueEntertime`.
- Add `Stats` struct
- Add `Stats` key to `Build` struct
- Remove duplicated `QueueEntertime` key in `Build`
- Fix references for `Build.QueueEntertime`
screwdriver-cd/screwdriver#2364

fix(2364): fix to read `build.QueueEntertime`

---

data/emitter
launch.go
launch_test.go

Currently, event meta is only set if none of the other cases are true (join, one parent build, parent event). This can cause problems when the user wants to get keys from event meta as well.
This PR always merged event meta first, then handles other cases.
N/A

fix: Always merge event meta first

---

launch.go
launch_test.go

If there is a metadata key conflict between eventmeta and parentbuildmeta, metadata should take parentbuildmeta.
However, current metadata takes eventmeta value. ( screwdriver-cd/screwdriver#2422 )
We fix the priority of meta value.
[mergemap](https://github.com/peterbourgon/mergemap) merges the src map into the dst map.
If there is a key conflict, it takes the src value.
[mergemap takes first arg as dst.](https://github.com/peterbourgon/mergemap/blob/e21c03b7a721e413718d2703181ead350d3c9d6f/mergemap.go#L17)
We should reverse the order of deepMergeJSON arg.
screwdriver-cd/screwdriver#2422
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …

fix(2422): Fix the order of meta merge.

---

executor/executor.go
go.mod
go.sum

Launcher uses a package whose repository has already disappeared 
This PR removes the dependency of myesui/uuid.v1[https://github.com/myesui/uuid] and adds google/uuid[https://pkg.go.dev/github.com/google/uuid] which is compliant with RFC 4122 and DCE 1.1
sample to generate v4 uuids with both pkgs
```package main
import (
"fmt"
uuidnew "github.com/google/uuid"
uuidold "gopkg.in/myesui/uuid.v1"
)
func main() {
guid := uuidold.NewV4().String()
guid1 := uuidnew.Must(uuidnew.NewRandom()).String()
fmt.Printf("uuids %v %v", guid, guid1)
fmt.Printf(" length %v %v", len(guid), len(guid1))
}
// output: uuids 8c046b9c-537b-4efc-add0-be88b9fffa01 da6fb1b0-a5e0-4fc4-9cb0-182e608d02c8 length 36 36
```
https://github.com/screwdriver-cd/screwdriver/issues/2475
I confirm that this contribution is made …

feat: remove myesui/uuid.v1 and add google/uuid

---

Dockerfile

We check for differences in dependent packages when updating components. As for launcher, there is no way to confirm which version of the tool is installed in an image, and it is difficult to clarify the range to be checked.
This PR allows you to view the installed tool version in a simple format.
```
/opt/sd # cat tool-versions
launcher v6.0.133
log-service v0.0.44
meta-cli v0.0.46
sd-step v0.0.19
sd-cmd v0.0.45
store-cli v0.0.64
```

feat: output tool versions on build

---

Dockerfile
Dockerfile.local

Fix launcher's unstable build.
The launcher uses gpg keyserver to verify tini, but with a high probability it fails and the build is unstable.
Therefore, add the keyserver by referring to the comments below.
https://github.com/krallin/tini/issues/124#issuecomment-420578042
Also, launcher uses bintray to get the hab command, but it seems that it is not available now.
```
$ wget -O hab.tar.gz 'https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-0.79.1-20190410220617-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux'
--2021-07-12 01:55:08--  https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-0.79.1-20190410220617-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
Resolving api.bintray.com (api.bintray.com)... 75.126.118.184
Connecting to api.bintray.com …
```

fix: Unstable docker build

---

launch.go
launch_test.go

meta data set on `build` key is now lost because it's overwriting build key.
https://github.com/screwdriver-cd/launcher/pull/421#discussion_r669215113
We should set properly `build` key meta.
I fixed to deepMerge parent `build` meta and default `build` meta.
If there are the same keys, it should use default `build` meta.
Otherwise, it should set parent `build` meta.
https://github.com/screwdriver-cd/screwdriver/issues/2501

fix(2501): Fetch parent meta.build if the key is not reserved

---

Dockerfile

gitversion is used in SD CI multiple times. There are cases when git returns 429 when SD is making too many calls to Github Eg: https://cd.screwdriver.cd/pipelines/1825/builds/725530/steps/init
Cache gitversion cli in `launcher` so that it can be reused in builds

feat: add gitversion for launcher

---

launch_test.go

We have not been able to cover all the cases of unit tests for metadata priorities.
https://github.com/screwdriver-cd/launcher/blob/661a96dc0903eae9dc9fb1b1ada46ab8b6139ae6/launch_test.go#L994-L1500
To test the correctness of the [mergedMeta overwrite order](https://github.com/screwdriver-cd/launcher/blob/661a96dc0903eae9dc9fb1b1ada46ab8b6139ae6/launch.go#L440-L521
), I created the following six test cases.
- TestMetaWhenStartPipeline
- TestMetaWhenTriggeredFromParentBuildWithoutParentBuildMeta
- TestMetaWhenTriggeredFromPipelinesByANDLogicWithParentBuildMeta
- TestMetaWhenTriggeredFromInnerPipelineByORLogicWithParentBuildMeta
- TestMetaWhenTriggeredFromExternalPipelineByORLogicWithParentBuildMeta
- TestMetaWhenStartFromAnyJobWithParentEvent
Also, duplicate and unnecessary tests have been …

fix:Metadata unit tests

---

Docker/launcher_entrypoint.sh
executor/executor.go

Currently, `/bin/jq` is readonly and users cannot overwrite it. We do not want the build system to occupy areas that is often used by users.
I created a `/usr/sd/bin` directory and put links of jq and bash in it. Then I added `/usr/sd/bin` to the `$PATH`.
[#2529](https://github.com/screwdriver-cd/screwdriver/issues/2529)
[docs of hab-pkg-binlink](https://docs.chef.io/habitat/habitat_cli/#hab-pkg-binlink)

fix: (2529) Make /bin/jq writable

---

Docker/launcher_entrypoint.sh

Last time, we moved `jq` and `bash` to `/usr/sd/bin/`.
https://github.com/screwdriver-cd/launcher/pull/426
However, [the launcher needs `/bin/bash`](https://github.com/screwdriver-cd/launcher/blob/588f5583aee19838480396b7bd039ff3f96e4ac1/Docker/run.sh#L1), and if the build use an image where `/bin/bash` does not exist (e.g. [alpine/opencv](https://hub.docker.com/r/alpine/opencv)), the build will not start.
There are more users using images that do not have `/bin/bash` than we might think.
There are many users who install `jq` in the user step, but the number of users who install `bash` should be close to zero. We can install bash in `/bin/bash` and it won't cause any problems.
Move `/usr/sd/bin/bash` to `/bin/bash`.
https://github.com/screwdriver-cd/screwdriver/issues/2529 …

Move /usr/sd/bin/bash to /bin/bash

---

executor/executor.go

As a user, I want to access the current step name from code executing within the step. 
Add new environment variable SD_STEP_NAME set before each ordinary step is executed run. Only set for ordinary user steps, not setup or teardown commands (during teardown, SD_STEP_NAME would be set to the last successfully executed step). If desired I could change this behavior.

feat: add SD_STEP_NAME env variable

---

executor/executor.go
launch.go
launch_test.go

Fix as discussed in https://github.com/screwdriver-cd/screwdriver/issues/2754.
The launcher now updates the build status when a pod is sent a SIGTERM via soft evict or kubectl delete.
I experimented in kubernetes v1.22.9 environment.
Before the fix, the build status is not updated during soft evict, so the status remains RUNNING. buildCluster-queue-worker doesn't send delete request, so build pod stays.
After fixing, the build status will be updated to Failure when soft evict. At this time, the buildCluster-queue-worker can sends a delete request to clean up the build pot.
What this PR doing:
- export TerminateSleep function
- remove terminateSleep before build status's update
- decomposed the function of `exit` into `cleanExit` and `prepareExit`
- `launch` function returns `sourceDir` …

fix(2754): Update build status if SIGTERM is received

---

launch.go
launch_test.go

The metadata `event.creator` was added in [this PR](https://github.com/screwdriver-cd/models/pull/532).
But this value is overwrote by the parent event's value, so we cannot get the correct value when run a build by `(Re)Start pipeline from here`.
This PR changes the metadata `event.creator` to be set in the launcher as in `build.buildId`.

feat: add default event meta

---

launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

We can change bookends for each build cluster. Users also want to change the process for each build cluster.
Add environment variable of build cluster name.

feat: add environment variable of build cluster name 

---

launch.go
launch_test.go

build warning should be specific to the build
exclude build warning from inheriting to downstream builds

fix(2878): exclude warning from merging build meta

---

launch.go
launch_test.go

If there are multiple projects in one repository, the source directory can be set for the pipeline, but the source directory is not set for the project name in SonarQube.
In SonarQube UI, it is not possible to distinguish which directory the project was created from, so modify the source directory so that it is set to the project name.
In pipelines where the source directory is set, modify it so that it is set in the format `repositoryName:sourceDir:jobName`.

feat: Add source directory to Sonarqube project name

---

screwdriver/screwdriver.go

Sometime, k8s node name is not output in `sd-setup-init` step log.
Implements of https://github.com/screwdriver-cd/screwdriver/issues/2882#issuecomment-1649346764 .
https://github.com/screwdriver-cd/screwdriver/issues/2882

[1] fix(2882): Update build status with k8s hostname together

---

Dockerfile

when using disk cache on arm64 instance will result in the wrong zstd cli being called
download the right zstd cli

fix: download right arch for zstd

---

executor/executor.go

provide bin path to statically linked executables

fix: add /usr/sd-static/bin to PATH

---

executor/executor.go

In sd-local, there was a bug that the sd-setup-launcher command and output was displayed in the job step as follows when using images such as centos7 with `/bin/sh` as `bash`.
The reason for this is that the `echo ;` at the end of the sd-setup-local command is a return condition, so the output of the command is left out and displayed in later job steps.
```
INFO   [0000] Prepare to start build...                    
INFO   [0012] Pulling docker image from centos:centos7...  
sd-setup-launcher: set -e && export PATH=${PATH}:/opt/sd:/usr/sd/bin:/usr/sd-static/bin && finish() { EXITCODE=$?; tmpfile=/tmp/env_tmp; exportfile=/tmp/env_export; export -p | grep -vi "PS1=" > $tmpfile && mv -f $tmpfile $exportfile; echo $SD_STEP_ID $EXITCODE; } && trap finish ABRT EXIT;
sd-setup-launcher: echo ; …
```

fix: Fix sd-local display bug

---

executor/executor.go

#465 was insufficient so the sd-local user step still included the output of the sd-setup-launcher step.
The reason is that the output of the sd-setup-laucher command changes depending on the job image.
In some images, the output of `echo ;` was not empty and contained a prompt characters such as `$` and `#`, which could cause the loop to be stuck.
The goal is that the sd-local user step does not include the output of the sd-setup-launcher step.
As a result of the fixes, it now works as follows.
Before
```
sd-setup-launcher: set -e && export PATH=${PATH}:/opt/sd:/usr/sd/bin:/usr/sd-static/bin && finish() { EXITCODE=$?; tmpfile=/tmp/env_tmp; exportfile=/tmp/env_export; export -p | grep -vi "PS1=" > $tmpfile && mv -f $tmpfile $exportfile; echo $SD_STEP_ID $EXITCODE; } && trap finish ABRT …
```

fix: refix sd-local display bug

---

screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

This PR is for https://github.com/screwdriver-cd/screwdriver/issues/2952#issuecomment-1809697640.
Pipeline build with rootDir containing `%` fails at `sd-setup-launcher` step.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```
`url.Parse()` fails at the point where it encodes `%`, so replace `%` with `%25` before that.

fix(2952): encode percent of rootDir

---

launch.go
launch_test.go

Cannot start build if rootDirectory contains a colon.
I fix to correctly parse rootDirectory even if it contains a colon
issue: https://github.com/screwdriver-cd/screwdriver/issues/2952
PR:
- https://github.com/screwdriver-cd/scm-github/pull/220
- https://github.com/screwdriver-cd/scm-base/pull/96
- https://github.com/screwdriver-cd/data-schema/pull/544

fix(2952): Allow colon to be used in root directory

---

executor/executor.go

Please refer to https://github.com/screwdriver-cd/screwdriver/issues/2973
Some environment(especially when using xterm), setup-launcher step is stuck.
Currently [doRunSetupCommand](https://github.com/screwdriver-cd/launcher/blob/ec83f2eb7078503c72eb151a42eb188a6285928a/executor/executor.go#L107), which read setupCommands output until it finds an empty line, can't detect the empty line correctly when xterm is set, because the output has terminal sequences as prefix like following.
```
\x1b[?2004l\r
```
Fix setup-launcher not to stuck even if using xterm.

fix(2973): setup commands stuck with xterm

---

launch.go
launch_test.go

During a restart case, sometimes the metadata from parentEvent is expected but with the current implementation, the metadata from parentBuildId wins over that from a parentEvent, ending in a situation where some metadata is missing.
This PR always merges parent event meta if it exists. Order of precedence goes: build > parent event > parent build > event
Related to https://github.com/screwdriver-cd/screwdriver/issues/3234

fix(3234): Always merge parent event meta last

---

launch.go

Screwdriver build shell is interactive. The build is stopped when the step requires user input.
Setting `GIT_ASKPASS=echo` until https://github.com/screwdriver-cd/screwdriver/issues/1583#issuecomment-2451234577 is resolved.
`GIT_ASKPASS` command is called when `git` commands need user login and fill user name and password automatically.
[Ref: doc](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#:~:text=my/repo.-,GIT_ASKPASS,-is%20an%20override)
Set `GIT_ASKPASS=echo` means filling username and password blank.
Thus we can fail fast the build.
- With `GIT_ASKPASS`: https://cd.screwdriver.cd/pipelines/15502/builds/965087/steps/sd-setup-scm
- No `GIT_ASKPASS`: https://cd.screwdriver.cd/pipelines/15502/builds/965086/steps/sd-setup-scm …

fix: set GIT_ASKPASS=echo

---

launch.go
launch_test.go

The behavior of [commit](https://github.com/screwdriver-cd/launcher/pull/475) might cause metadata from parent event to overwrite the metadata from the current event and the predecessor builds. 
The parent event metadata should always be the predecessor of parentBuilds and event metadata because the parentEvent should happen before the current event or the predecessor builds (except for the case of restart from remote trigger)
https://github.com/screwdriver-cd/screwdriver/issues/3234

feat(3234): parentevent should be a predecessor of other metadata

---

launch.go
launch_test.go

The current implementation of meta behavior causes the merging of parentEvent and event altogether whenever they are available. 
This implementation should not be necessary, instead event and parentEvent meta should be mutually exclusive. The parentEvent will only be relevant for the initial build of the restart. Afterward, it will simply be part of the event, as the first build will update the event appropriately during the launcher exit.
https://github.com/screwdriver-cd/screwdriver/issues/3234

feat(3234): event and parentEvent meta should be mutually exclusive

---

launch.go
launch_test.go

On the case of event restarted, when event meta is not empty, the metadata from parent event will be ignored and this is not the expected behavior. 
Fix the expected behavior to always allow parent event metadata to be merged as predecessor of other metadata, i.e. event meta, parent builds. 
https://github.com/screwdriver-cd/screwdriver/issues/3234

fix(3234): always allow parent event metadata to be merged during the build

---

Dockerfile

https://github.com/screwdriver-cd/store-cli/pull/82 introduced the 5 seconds timeout for waiting for SD store to return 100 status code before sending over the payload when it sends an `Expect` header.
This change caused the launcher to bring in new release of store cli which ALWAYS stalls for 5-seconds because the store doesn't handle the `Expect` header in endpoints (e.g. build artifacts) other than the cache, see [this](https://github.com/screwdriver-cd/store/pull/146)
Pin the version of store-cli in launcher to v0.0.71 until the store can handle the `Expect` header for other endpoints.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on …

fix: pin version of store-cli to v0.0.71

---

launch.go
launch_test.go
screwdriver/screwdriver.go
screwdriver/screwdriver_test.go

Currently, if the parent builds have same key metadata, the value of the build completed earlier is used.
(Not value of the build completed later)
This behavior is a little strange.
Sort merging parent builds metadata order by their finished time.
https://github.com/screwdriver-cd/screwdriver/issues/3125#issuecomment-2458897936

fix(3125): merge parent build meta order by end time

---

Dockerfile

There was an issue with store-cli where it would wait for 5 seconds during uploads if there was no handling for the Expect header.
This has been fixed in the following PR: https://github.com/screwdriver-cd/store-cli/pull/83
Therefore, I would like to update the store-cli to the latest.
I would like to revert the fixed version back to the latest.
https://github.com/screwdriver-cd/launcher/pull/482
https://github.com/screwdriver-cd/launcher/pull/482
https://github.com/screwdriver-cd/store-cli/pull/83

fix(482): Bump store-cli version to the latest.

---

launch.go

It is currently difficult to determine the root cause when a launcher fails, as no meaningful status message is provided when updating the build status to "fail." This lack of information complicates troubleshooting and delays issue resolution.
This PR ensures that a detailed status message is included whenever a build status is updated to "FAILURE" during the launch action. The status message will provide relevant details about the failure, making it easier to identify and resolve the underlying issue quickly, as well as to create alerting system based on logs. 
https://github.com/screwdriver-cd/screwdriver/issues/3248
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority …

feat(3248): add status message to update build when launcher failed

---

launch.go
launch_test.go

The current logic appears to skip merging external metadata when the parentBuilds length is 1 or less, which does not seem correct or appropriate.
Implement a temporary adjustment to relax the condition to facilitate further troubleshooting.
N/A 

fix: temporary relax join for troubleshooting

---

launch_test.go

The [last commit for relaxing the requirement to join external meta](https://github.com/screwdriver-cd/launcher/pull/488) had ignored the unit test to speed up troubleshooting purpose. 
This PR is to fix the failed unit test after the change made. 
https://github.com/screwdriver-cd/screwdriver/issues/3125

fix(3125): add tests after relaxing the requirement to join external meta

---

launch.go
launch_test.go

After https://github.com/screwdriver-cd/launcher/pull/493, the meta.sd.pr.* values are missing when the build is triggered by pr-closed.
I fixed this bug.
Retain pr-closed info meta in launch process.
https://github.com/screwdriver-cd/screwdriver/issues/3235

fix(3235): Retain metadata for pr-closed info
