- incrementVersion.sh
- wercker.yml
This script will increment the patch number with every Wercker build.
VERSION file gets updated with new value.
> Add shell script to auto increment version number

- wercker.yml
Generate SSH key pair and add step in order to use git fetch/push
> Add SSH key step to pipeline

- wercker.yml
Accidentally deleted this line from my previous PR =/
> Add 'steps' line under deploy

- wercker.yml
This should enable the "add-to-known-hosts" step to run
> Add 'install-packages' step to install openssh-client.

- wercker.yml
This should properly create a new tag
> Use lightweight tags instead of annotated tags

- wercker.yml
- Sets up the Go workspace
- Gets all external packages
> Fix wercker build pipeline

- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
- `screwdriver` helper package
- Fetch a Build struct from a Build's ID
> Started screwdriver.API.BuildFromID

- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
Also refactored the Authorization header test to de-dupe
> Added handling of non-200 responses from Screwdriver gets

- wercker.yml
- Moves the launch file to the original source directory so it can be uploaded.
> Fix wercker deploy pipeline

- launch.go
- launch_test.go
- screwdriver/screwdriver.go
Also did some refactoring of URL handling to make for more consistent URLs
> Added workspace creation

- README.md
- git/git.go
- git/git_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- Calling out an explicit dependency on /v3
- Checking out a desired branch
- Adding logging to startup and git clone
- Allow alternative workspace directory
- Support token loading from environment
> Some more enhancements

- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
> Added Screwdriver YAML parsing via the /validator endpoint

- git/git.go
- git/git_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
Adds functionality for checking if job name is a PR, then fetching and merging if so.
Addresses #15. (except updating job name)
> Add checkIfPR, Fetch, and Merge functions

- launch_test.go
> More coverage for launch

- executor/executor.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
- Array of commands instead of hash of key/value pairs
- Also cleaned up some docs and logs
> Switching to the new steps/commands layout

- launch.go
- launch_test.go
This PR adds in a helper function called `writeArtifact` that can be used to write objects to disk.
It's being used to write the screwdriver job steps and environment to the artifacts directory in a json file
> Write steps/environment to artifacts folder

- git/git.go
> No longer changing directories back after setting up git

- README.md
- executor/executor_test.go
- launch_test.go
- screwdriver/screwdriver_test.go
- Also ran gofmt -s to get the report up to 100%
> Added a goreportcard badge to the README

- git/git.go
- git/git_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
Calls "git reset --hard [sha]" after cloning to ensure HEAD points to correct commit.
> Add git reset function

- git/git.go
- git/git_test.go
- launch.go
- launch_test.go
Initial stab at refactoring the git package
> Refactor git package

- executor/executor.go
- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver.yaml
- screwdriver/emitter.go
- screwdriver/emitter_test.go
- screwdriver/screwdriver.go
screwdriver.Emitter is an io.WriteCloser that will be used to read stdout/error and write it to a file
> screwdriver.Emitter to emit logs to file

- executor/executor.go
- executor/executor_test.go
- screwdriver/emitter.go
- Also changed to mS instead of μS in the log times
> Adding the command that is being executed to the Emitter output

- launch.go
- launch_test.go
Adds the environment variables specified in #57 with their default values.
> Add default environment variables in launch

- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
This blocks https://github.com/screwdriver-cd/screwdriver/pull/153
> [minor] Moving to updating build status by PUTing to /builds/:id

- executor/executor.go
- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
- Also removing SD_TOKEN from the environment to prevent accidental
leakage
- Refactored the environment code a little bit while I was at it
Fixes https://github.com/screwdriver-cd/launcher/issues/72
> Fetching build secrets and putting them into the environment

- executor/executor.go
- executor/executor_test.go
- It got stripped out in the last PR accidentally
- Added a test for this case
- The whole thing is ripe for refactoring
> Added job environment overrides back in to the launcher

- README.md
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
This allows us to now use the V4 API
> Switching to V4 API [major]

- git/git.go
- git/git_test.go
- launch.go
- launch_test.go
Also cleaned stuff up. It may be easier to review 1 commit at a time.
- Refactored git operations to be methods on `repo`
- Added a test for git.New
> Resetting the repo to its SHA after checkout

- README.md
We are moving all issues to screwdriver-cd/screwdriver
> Show version not issues

- Dockerfile
Also switching to web instead of API calls (as it breaks in Docker Hub sometimes due to rate limiting)
> Adding Fifo and Log Service

- Dockerfile
This isn't needed and I want to save 800+ bytes. :)
> Remove extra gpg check file

- screwdriver.yaml
> Adding .sh

- executor/executor.go
- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
We can get the commands and environment of a build from a build instead of a job for more up to date information
> Get commands and environment from build instead of job

- executor/executor.go
- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
BREAKING CHANGE: Will no longer accept alphanumeric string IDs
Epic: https://github.com/screwdriver-cd/screwdriver/issues/399
> feat(399): Switching from Hash IDs to Numeric IDs [MAJOR]

- README.md
This is also to bump the version (since it didn't before).
> Updating README.md to reflect ID change [major]

- launch.go
- launch_test.go
We need this environment variable
> fix: expose token ENV

- executor/executor.go
- executor/executor_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
Reverts screwdriver-cd/launcher#115
Related: https://github.com/screwdriver-cd/screwdriver/issues/473
> Revert "feat(473): Always run steps with the alwaysRun flag true"

- launch.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
Resolves https://github.com/screwdriver-cd/screwdriver/issues/681
> fix: expose eventId

- Dockerfile
fix syntax err for adding gpg server
Reference: https://github.com/screwdriver-cd/launcher/blob/master/Dockerfile
> fix: fix syntax for adding gpg server

- README.md
Need a new commit to rebuild/pull in the new meta-cli https://github.com/screwdriver-cd/meta-cli/pull/11
> fix: pull in new meta-cli

- launch.go
- launch_test.go
Expose this value per some user's request
> fix: expose SD_BUILD_SHA

- launch.go
- launch_test.go
Reverts screwdriver-cd/launcher#139 since launcher now works https://github.com/screwdriver-cd/launcher/pull/140
> fix: pull back #137

- habitat/plan.sh
The hab builder doesn't have Git installed.  So get the latest info from
GitHub releases page.
> fix: Load version from GitHub releases page

- habitat/plan.sh
- screwdriver.yaml
Making the plan more standard.  Also putting the compiled binary into the artifact dir for local testing.
> fix(habitat): Making habitat plan more dynamic

- Dockerfile
This stores everything in `/hab` since Habitat doesn't support alternative root directories.  After this, we can mount `/hab` into the build container and have access to pre-installed packages (like bash, git, and more!).  Additionally, teams running their own cluster can install their own packages as well.
_Note: increases size from 38mb to 91mb 😞 _
Related to: https://github.com/screwdriver-cd/screwdriver/issues/877
> feat(habitat): Putting all Habitat files in /hab

- .gitignore
- glide.yaml
- screwdriver.yaml
Use glide for dependency management
> chore: use glide for dependency management

- executor/executor.go
The current proposal for implementing a build timeout requires that tear-down commands always be executed when the build times out. This refactor splits the set of commands up as such.
Split the user-defined steps and the tear-down steps. Process the user-defined commands first, then process the tear-down steps.
> refactor: separate processing of user-defined steps and teardown steps

- executor/executor.go
Log build timeout events for better clarity on the timeout execution
> chore: log some of the build timeout events

- executor/executor.go
The current build timeout notification looks like this
Improve the timeout message by making it more pronounced
> refactor: improve build timeout handler

- CONTRIBUTING.md
to pull in the latest `sd-cmd` acutally
https://github.com/screwdriver-cd/sd-cmd/pull/16
> fix: link to contribution docs

- README.md
Need a new commit to rebuild/pull in the new sd-cmd https://github.com/screwdriver-cd/sd-cmd/pull/17
> fix: pull in new sd-cmd

- README.md
To pull in new log-service: https://github.com/screwdriver-cd/log-service/pull/19
> fix: to pull in new log-service

- executor/executor_test.go
- launch.go
- launch_test.go
Simple implementation of https://github.com/screwdriver-cd/screwdriver/issues/1229
> feat: use configurable shell

- executor/executor.go
- executor/executor_test.go
Thanks @jithin1987  for suggestion
This is to fix newline in ENV or SECRET
Related: https://github.com/screwdriver-cd/screwdriver/issues/1192
> fix: newline escape

- executor/executor.go
- executor/executor_test.go
Related: https://github.com/screwdriver-cd/screwdriver/issues/1217
> fix: allow wrap for teardown

- executor/executor.go
For some reason: https://github.com/screwdriver-cd/launcher/commit/8d53baa67661d5e2e7c38d5c3ab9afe814799e75 did not work
> fix: source if file is available

- executor/executor.go
- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
Blocked By:
- https://github.com/screwdriver-cd/data-schema/pull/297/files
- https://github.com/screwdriver-cd/models/pull/302
- New API deployment
Related: https://github.com/screwdriver-cd/screwdriver/issues/1382
> [3] fix: expose pr parent job

- launch.go
- launch_test.go
Related: https://github.com/screwdriver-cd/screwdriver/issues/1483
> feat(1483): add default metadata

- data/emitter
- executor/executor.go
- executor/executor_test.go
> fix: ignore errors with invalid env variables

- Docker/run.sh
- launch.go
- launch_test.go
Adding SD_UI_URL
https://github.com/screwdriver-cd/screwdriver/issues/1555
> feat(1555): Add SD_UI_URL

- executor/executor.go
- executor/executor_test.go
- launch.go
- launch_test.go
> feat(1070): evaluate environment variables

- launch.go
- launch_test.go
> fix: add default cluster env

- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
Will revert this and make this a major version bump
> fix: Revert "fix: accept env as array. BREAKING CHANGE: build environment is now an array"

- executor/executor_test.go
- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_test.go
> fix: accept env as array. BREAKING CHANGE: build env is now an array

- launch.go
- launch_test.go
With our current logic, we always merge the build meta with the parentBuildMeta. If the parentBuild is an external build, it write the merged meta to external meta file. There are two problems with that. First the build won't have its own meta file, second the default meta fields in the external meta will be overwritten by the the new build's meta which is not correct.
This PR will fix this by writing to external meta file without merging. And write the new build's meta to its own meat file.
> fix: write to both external trigger meta file and build meta file

- launch.go
this change broke something, will try to build locally first
> fix: cmdPath when running with sourceDir

- launch.go
cache-compress and cache-md5check args to be converted to bool
[1830]
> fix(1830): fix cli boolean flag arg

- screwdriver.yaml
Pull latest store-cli changes related to pretty-print JSON logs 
[1830](https://github.com/screwdriver-cd/screwdriver/issues/1830)
[PR-52](https://github.com/screwdriver-cd/store-cli/pull/52)
> fix(1830): pull latest store-cli

- launch.go
- launch_test.go
Fixes https://github.com/screwdriver-cd/screwdriver/issues/1926
> fix(1926): Add SD_UI_BUILD_URL

- Docker/run.sh
fix the sh syntax
fix the sh syntax
> fix: use more generic sh syntax

- Docker/run.sh
fix syntax
[Evaluate Kata Containers over HyperD](https://github.com/screwdriver-cd/screwdriver/issues/818)
> feat(818): generic sh sytax

- Docker/run.sh
- launch.go
- launch_test.go
Fix this Issue.
https://github.com/screwdriver-cd/screwdriver/issues/2116
Change `PUSHGATEWAY_URL` to `SD_PUSHGATEWAY_URL`.
https://github.com/screwdriver-cd/screwdriver/issues/2116
[1] https://github.com/screwdriver-cd/executor-k8s/pull/129
[2] https://github.com/screwdriver-cd/executor-k8s-vm/pull/74
[3] https://github.com/screwdriver-cd/launcher/pull/361 <- this PR
> fix(2116): [3] Change PUSHGATEWAY_URL to SD_PUSHGATEWAY_URL

- data/emitter
- launch.go
- launch_test.go
> fix: correct string parsing

- data/emitter
- screwdriver/screwdriver.go
Two Until tests related to time format are failing when running locally
Fix tests `TestUpdateStepStart` & `TestUpdateStepStop` when running locally 
> fix: make tests work in local where timezone is not UTC

- Docker/launcher_entrypoint.sh
Simplify trap signal cleanUp function.
https://github.com/screwdriver-cd/launcher/pull/372
https://github.com/screwdriver-cd/launcher/pull/373
> fix: simplify trap signal func

- Docker/launcher_entrypoint.sh
Noticing a build failure where `binary_exist` is not working as expected
> fix: ignore symlink error

- Docker/launcher_entrypoint.sh
- Dockerfile
Add Zstandard hab package and binlink
https://github.com/screwdriver-cd/store-cli/pull/66
> fix: add Zstandard hab package and binlink

- Dockerfile
fix typo
https://github.com/screwdriver-cd/launcher/pull/393/files
> fix: cleanup zstd tar.gz files

- executor/executor.go
Revert https://github.com/screwdriver-cd/launcher/pull/388
https://github.com/screwdriver-cd/launcher/pull/388
> fix: revert capturing user step env variables

- go.sum
go.sum changes after `go mod tidy` (go1.16) - minor change
> changes in go.sum after 'go mod tidy'

- executor/executor.go
Environment variables are not available in teardown steps.
Abort or Timeout doesn't capture the environment variable in teardown steps when `sleep` command is used in the sd step.  `sleep` is not killed via the SIGABRT signal and keeps running in the background. Explicitly kill `sleep` command for abort (or) timeout signal and after all teardown steps are executed.
https://github.com/screwdriver-cd/screwdriver/issues/2351
https://github.com/screwdriver-cd/screwdriver/issues/2361
https://github.com/screwdriver-cd/launcher/pull/404
> fix(2351): teardown steps do not get the environment variables

- Docker/launcher_entrypoint.sh
Do not hard code shell to `bash.` Use bash if exist, else default to `sh`
> fix: try to use bash shell for launcher

- .goreleaser.yml
- Dockerfile
- screwdriver.yaml
Screwdriver needs to support arm64 containers for building
This PR builds the Screwdriver launcher image for multiple platforms 
> feat: Build docker image for multiple platforms

- launch.go
- launch_test.go
- screwdriver/screwdriver.go
- screwdriver/screwdriver_local.go
- screwdriver/screwdriver_local_test.go
- screwdriver/screwdriver_test.go
To determine that the pipeline is private or not, we add an environment valuable `SD_PRIVATE_PIPELINE`.
If the pipeline is private, set `true` on `SD_PRIVATE_PIPELINE`.
Otherwise, set `false` on `SD_PRIVATE_PIPELINE`.
https://github.com/screwdriver-cd/screwdriver/issues/2520#issuecomment-1092594858
> feat(2520): Add env for private pipeline

- Dockerfile
- Dockerfile.local
grep was broke because old url does not contain download link
resort to github api instead
> fix: update github link

- Dockerfile
Support sonar-scanner cli on macosx aarch64 
This PR adds sonar-scanner-any 
[](https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/)
> add sonar-scanner-any

- Dockerfile
update sonar cli to latest version
This PR updates sonar-scanner-cli to latest version
https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/scanners/sonarscanner/
> update sonar cli new version

- Docker/run.sh
cat /tmp/sd_event.json if exists
cat /tmp/sd_event.json if exists
> fix: cat optional file

- Docker/run.sh
> fix: ensure right event dumping

- launch.go
- launch_test.go
I want to obtain how much resources a build use.
Add information to push to prometheus.
> feat: Add resource info to push metrics

- Dockerfile
Updating docker file to use new sd-packages version for skopeo
Updating docker file to use new sd-packages version for skopeo
https://github.com/screwdriver-cd/sd-packages](https://github.com/screwdriver-cd/sd-packages/pull/10
> use new sd-package versions

- Dockerfile
Update launcher image with new versions for sd-packages
Update launcher image with new versions for sd-packages
https://github.com/screwdriver-cd/sd-packages/releases/tag/v0.0.38
> Update Dockerfile with new sd-pkg versions

- Dockerfile
We need to revert to older version of skopeo as it fails to work with rhel 8
> downgrade to older version of sd-packages

- Dockerfile
Update sd-packages version to v0.0.40
https://github.com/screwdriver-cd/sd-packages/releases/tag/v0.0.40
> update sd-packages to v0.0.40

- Dockerfile
silly mistake, used incorrect binary
> fix binary name

- Dockerfile
- Dockerfile.local
Upgrade sonarscanner cli
Upgrade sonarscanner cli
> fix: upgrade sonarscanner
